#Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Bookjjogeuro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  inhibit_all_warnings!  # pod에서 발생하는 워닝 무시

  # Pods for Bookjjogeuro
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Hero'
  pod 'SwiftLint'
  pod 'NMapsMap'
  pod 'Action'	
  pod 'NSObject+Rx'
  pod 'lottie-ios'
  pod 'RxDataSources'
  pod 'Kingfisher'

  # 카카오 로그인을 위한. Rx가 있네 띠용
  pod 'RxKakaoSDKAuth'
  pod 'RxKakaoSDKUser'

  # 파이어베이스
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'	
  pod 'Firebase/Core'
  # pod 'Firebase/Firestore'
  # pod 'FirebaseFirestoreSwift'
  # pod 'Firebase/Database'
  # pod 'GeoFire', '~> 4.0'
  # pod 'CodableFirebase'

end

# XCode12 라이브러리 추가시 최소버전이 9로 지정되어서 넣은 코드
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
