#Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'warmingUpProject_3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for warmingUpProject_3
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Hero'
  pod 'SwiftLint'
  pod 'NMapsMap'
  pod 'Action'	
  pod 'NSObject+Rx'
  pod 'lottie-ios'
  pod 'RxDataSources'
  pod 'Kingfisher'

  # 카카오 로그인을 위한. Rx가 있네 띠용
  pod 'RxKakaoSDKAuth'
  pod 'RxKakaoSDKUser'

  # 파이어베이스
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'	
  pod 'Firebase/Core'
  # pod 'Firebase/Firestore'
  # pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Database'
  pod 'GeoFire', '~> 4.0'
  pod 'CodableFirebase'

end
