# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'warmingUpProject_3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for warmingUpProject_3
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Hero'
  pod 'SwiftLint'
  pod 'NMapsMap'

end
